# Generated by Django 4.2.19 on 2025-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailcompany',
            name='recipients',
        ),
        migrations.AddField(
            model_name='emailcompany',
            name='recipients',
            field=models.ManyToManyField(related_name='emails', to='mailer.recipient'),
        ),
    ]
